import Link from "next/link";

export const metadata = {
  title: "RECIPE PAGE",
  description: "Generated by Next.js",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href={{ pathname: "/" }}>Home</Link>
          <Link href={{ pathname: "/about" }}>About</Link>
          <Link href={{ pathname: "/Recipes" }}>Recipes</Link>
          <Link href={{ pathname: "/contact" }}>Contact</Link>
          <Link href={{ pathname: "/login" }}>Login</Link>
        </header>

        {children}

        <footer>
        <Link href={{ pathname: "/privacy-terms" }}>Privacy</Link>
        <Link href={{ pathname: "/contact" }}>Contact</Link>
       
        <h3>&copy;Naod inc</h3>
      </footer>
      </body>
    
    </html>
  );
}
