import Link from "next/link";
import '../components/style.css'


export const metadata = {
  title: "MOVIE",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <header>
          <Link href={"/"}>Home </Link>
          <Link href={"/about"}>About</Link>
          <Link href={"/contact"}>Contact</Link>
          <Link href={"/category"}>Category</Link>
        </header>
        {children}
        <footer></footer>


      </body>
    </html>
  );
}
